### ISSUE TITLE
Plugin Activation: Call to a member function on a non-object

### ISSUE THREAD

**Issue by aaron13100** [aaron13100/404solution#12]
#### What I Expected To Happen
Plugin Activation doesn't work.

#### What Happened Instead
Plugin could not be activated because it triggered a fatal error.

Fatal error: Call to a member function errorMessage() on a non-object in /chroot/home/totalfoo/totalfood.com/html/wordpress/wp-content/plugins/404-solution/includes/ErrorHandler.php on line 36 Fatal error: Call to a member function errorMessage() on a non-object in /chroot/home/totalfoo/totalfood.com/html/wordpress/wp-content/plugins/404-solution/includes/ErrorHandler.php on line 69

(opened for @totalfood from issue #4)

**Comment by aaron13100** [comment]
@totalfood there should be a different message in version 1.6.4. Have you had a chance to try it?
thanks

**Comment by aaron13100** [comment]
There's been no response for 17 days so I'll assume the issue was solved or forgotten.

**Comment by scidave** [comment]
Hi Aaron

The plugin works fine on the test site (aieworld.com), but I cannot get it to activate on my science site.  Get the following fatal error wether I have the original "redirectioner" plugin active or not ...


Fatal error: Call to a member function readFileContents() on a non-object in /home/howthing/public_html/wp-content/plugins/404-solution/includes/DataAccess.php on line 54
ABJ404-SOLUTION Fatal error handler: {"type":1,"message":"Call to a member function readFileContents() on a non-object","file":"/home/howthing/public_html/wp-content/plugins/404-solution/includes/DataAccess.php","line":54}

Any ideas?

**Comment by aaron13100** [comment]
It's strange that it works on one site and not another, but I can imagine why this might happen.. I'll let you know when a fix is available.

**Comment by scidave** [comment]
Thanks Aaron

**Comment by aaron13100** [comment]
Hey Dave. Hopefully version 1.7.2 fixes this for you. It was released today. Otherwise let me know what the next error message says! :/ :) 
thanks

**Comment by scidave** [comment]
It activated just fine!  Thanks!

One question though ... I inactivated the original plugin before activating the new one.  Do I use the import tool function to get all the redirects that were done with the original plugin?

**Comment by aaron13100** [comment]
Yep. 404 Solution -> Tools -> Import 404 Redirected Data.

**Comment by scidave** [comment]
I tried it with the 404 Redirected plugin deactivated and activated and I get the same message when trying to import those into the new plugin

Error: No records were imported. SQL result: "Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_unicode_520_ci,IMPLICIT) for operation '='"

So I left both plugins activated for now

**Comment by aaron13100** [comment]
Dave, the activation doesn't matter. I'll let you know when a fix for this next bug is available. Thanks for finding all of these bugs by the way :) It's good to have some feedback. If you remember it's better to open a new issue for each separate error message. thanks!

**Comment by scidave** [comment]
Ok ... If I find another I'll start a new thread.  Tks!!

**Comment by aaron13100** [comment]
Hey Dave. Time to try again with version 1.7.3!

**Comment by scidave** [comment]
Activated again fine.  Looks like it imported everything fine as well.  So I deactivated 404 Redirected and will use 404 solution going forward.  No more error messages that I see so far.  Thanks !!!

**Comment by totalfood** [comment]
Aaron, I've been following along with the thread. Finally reactivated 404 Solution and everything imported perfectly. Very excited to finally start hacking away at all of the 404s that had been building up in 404 Redirected.

Scidave, thanks to you as well for reporting the bugs, and help Aaron troubleshoot. Good day to you both!
