### ISSUE TITLE
Add Regex redirects

### ISSUE THREAD

**Issue by aaron13100** [aaron13100/404solution#13]
From @pbowyer on January 31, 2017 9:30

Scenario

A site uses a CPT for events. Once the event is past they unpublish the CPT post, which every time creates a new 404 error.

Solution

Rather than create individual redirects, it would be great to create one regular expression rule for all matching 404's:

404s matching /events/.+ => /events/?finished=1
_Copied from original issue: ThemeMix/redirectioner number twenty nine.

**Comment by XGhozt** [comment]
Is this not possible at all right now? Can we use this plugin to do (obviously the wrong syntax:) "/something/*" ?

**Comment by aaron13100** [comment]
This will be possible in an upcoming version. (Right now it won't work)

**Comment by XGhozt** [comment]
To htaccess it is. Thanks.

**Comment by aaron13100** [comment]
This is done is version 2.6.0.
