### ISSUE TITLE
Redirecting from url leading slash

### ISSUE THREAD

**Issue by MadMaxxCZ** [aaron13100/404solution#22]
#### Steps to Reproduce the Bug
It's still showing in my logs

#### Debug Lines
2017-12-07 07:44:42 (INFO): Updating database version from 2.5.2 to 2.5.3 (begin).
2017-12-07 07:44:42 (INFO): Updating database version to 2.5.3 (end).

**Comment by aaron13100** [comment]
What is still showing in your logs?

**Comment by MadMaxxCZ** [comment]
Hi Aaron,

Thank you for getting to me so quickly.

I'm still getting these redirects. I've tried to rewrite .htaccess file,
deactivate almost all plugins, change theme, but something is still
redirecting urls to /https:/ instead of https://  See below:
[image: Vložený obrázek 1]

Is it possible to find where it came from?

Thank you.

2017-12-07 15:14 GMT+01:00 Aaron <notifications@github.com>:

**Comment by aaron13100** [comment]
So something is redirecting from pages that don't exist to a URL that starts with "/https:/" instead of "https://" ? 
Does this happen for all URLs or only for pages that don't exist?
Does this still happen when the 404 Solution plugin is disabled?

thanks

**Comment by MadMaxxCZ** [comment]
The urls exist, but in the right format. I've tried to disable your plugin and it seemed not happening, bit I'm not sure as I don't know how to find it without your plugin 😕 I will try it and let you know.

7. 12. 2017 16:39, 16:39, Aaron <notifications@github.com> napsal/a:

**Comment by aaron13100** [comment]
It seems like it's probably an issue with .htaccess. Maybe try renaming .htaccess to something else, restarting, and seeing if that fixes the issue.

**Comment by MadMaxxCZ** [comment]
OK, thank you, I will try it.

7. 12. 2017 19:37, 19:37, Aaron <notifications@github.com> napsal/a:

**Comment by aaron13100** [comment]
Did you get this figured out?

**Comment by MadMaxxCZ** [comment]
Still the same :-(

[image: Vložený obrázek 1]

2017-12-09 19:03 GMT+01:00 Aaron <notifications@github.com>:

**Comment by aaron13100** [comment]
Did you disable the plugin to see if the issue is still there with the plugin off ?

**Comment by MadMaxxCZ** [comment]
To be honest I don't know how to find it without the plugin...

11. 12. 2017 1:00, 1:00, Aaron <notifications@github.com> napsal/a:

**Comment by aaron13100** [comment]
If you go to a url, like `http://your_website.com/some_page.html`, and then it forwards you to `/http:/your_website.com/some_page.html`, then that's an issue, right? Is that correct, or not?

So just go to `http://your_website.com/some_page.html` to see if it's broken.

**Comment by MadMaxxCZ** [comment]
Yes, that's the issue. When I go through the web, it works normally, I can't even find the corrupted url in the html source code anywhere, but I wanted to know where it cames from

11. 12. 2017 16:47, 16:47, Aaron <notifications@github.com> napsal/a:

**Comment by aaron13100** [comment]
So then disable the plugin and go to the URL that should work, then tell me what happens.

**Comment by MadMaxxCZ** [comment]
Hi Aaron,

I'm so sorry, I found that this is not done by your plugin. I deactivated
it and installed 'Redirection" plugin and it is showing the same. I will
try to turn off all plugins. Is it possible to trace in your plugin where
it came from?

thanks

[image: Vložený obrázek 1]

2017-12-11 17:01 GMT+01:00 Aaron <notifications@github.com>:

**Comment by aaron13100** [comment]
Nope, it's not sorry. My plugin can only log what it does itself.
