### ISSUE TITLE
Breaks WP-CLI even when run from automated cron

### ISSUE THREAD

**Issue by juancaser** [aaron13100/404solution#25]
#### What I Expected To Happen
No error, wp-cli cron should run without any error

#### What Happened Instead
Fatal error: Uncaught Error: Call to a member function getOptions() on null in /home/..../wp-content/plugins/404-solution/includes/DataAccess.php:808

#### Steps to Reproduce the Bug
Run `wp cron event run --due-now`

#### Debug Lines

Stack Trace
`Fatal error: Uncaught Error: Call to a member function getOptions() on null in /home/.../wp-content/plugins/404-solution/includes/DataAccess.php:808
Stack trace:
#0 /home/.../wp-includes/class-wp-hook.php(286): ABJ_404_Solution_DataAccess::deleteOldRedirectsCron()
#1 /home/.../wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/.../wp-includes/plugin.php(531): WP_Hook->do_action(Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(288): do_action_ref_array('abj404_cleanupC...', Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(259): Cron_Event_Command::run_event(Object(stdClass))
#5 [internal function]: Cron_Event_Command->run(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(93): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher in /home/.../wp-content/plugins/404-solution/includes/DataAccess.php on line 808
	ABJ404-SOLUTION Fatal error handler: {"type":1,"message":"Uncaught Error: Call to a member function getOptions() on null in /home/.../wp-content/plugins/404-solution/includes/DataAccess.php:808
Stack trace:
#0 /home/.../wp-includes/class-wp-hook.php(286): ABJ_404_Solution_DataAccess::deleteOldRedirectsCron()
#1 /home/.../wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters('', Array)
#2 /home/.../wp-includes/plugin.php(531): WP_Hook-&gt;do_action(Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(288): do_action_ref_array('abj404_cleanupC...', Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(259): Cron_Event_Command::run_event(Object(stdClass))
#5 [internal function]: Cron_Event_Command-&gt;run(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(93): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher","file":"/home/.../wp-content/plugins/404-solution/includes/DataAccess.php","line":808}, Additional info: (none)`

**Comment by aaron13100** [comment]
Hey @thejuanwhocode, thanks for the stacktrace. Do you have version 2.18.0?  I can't seem to find a line that corresponds to the error message.

**Comment by aaron13100** [comment]
If you don't have the latest version, please upgrade and try again.

If you do have the latest version, would you please click on the "Tools" tab and scroll to the bottom to click "Run Maintenance" and then send me the error message from the debug file. The debug file is at 404 Solution -> Options -> Advanced Settings Etc -> View the debug file.

thanks

**Comment by juancaser** [comment]
> If you don't have the latest version, please upgrade and try again.
> 
> If you do have the latest version, would you please click on the "Tools" tab and scroll to the bottom to click "Run Maintenance" and then send me the error message from the debug file. The debug file is at 404 Solution -> Options -> Advanced Settings Etc -> View the debug file.
> 
> thanks

thanks man, will check tommorow see if it now works!

**Comment by juancaser** [comment]
It works i dont have any error anymore... i let it run for couple days via cronjob and run it manually so far its not breaking the wp-cli anymore, the update did its job, will push this update to our production now.
