### ISSUE TITLE
Error when trying to change site for all unknown 404s

### ISSUE THREAD

**Issue by nikolailehbrink** [aaron13100/404solution#27]
#### What Version I'm Using
2.23.3

#### What I Expected To Happen
That the plugin lets me change the site to which a user should be redirected after he enters a wrong url
![Screenshot 2020-10-20 101400](https://user-images.githubusercontent.com/38915700/96559214-05c75300-12bd-11eb-8f8a-4cd01eb59795.png)

#### What Happened Instead
Error  Message: "Task failled successfully (:D)" shows up and the previous  entered site is changed to "Standard 404-Site"

#### Steps to Reproduce the Bug
I just created some 301 redirects before that step and than wanted to change that setting

**Comment by aaron13100** [comment]
Please try version 2.23.4

**Comment by aaron13100** [comment]
I guess this has been fixed.
