### ISSUE TITLE
Getting issue with adding redirect

### ISSUE THREAD

**Issue by maniish** [aaron13100/404solution#28]
I am getting the following error while adding any redirect to an external site.

Error: Data not formatted properly.
Error: unable to add new redirect.

#### What Version I'm Using
Plugin version: 2.23.8, PHP: 7.2.34, WordPress: 5.6.2, MySQL: 5.7.33, WP Memory Limit: 40M, mbstring Extension: true

**Comment by aaron13100** [comment]
I was able to add a redirect on my test site. Please turn on debug logging (404 Solution -> Settings -> Options -> Advanced Etc -> Debug logging (check the box)). Click save at the bottom. Try to create a redirect again. View the debug log (from the settings page), paste the entire debug log or the last 20 pages to https://pastebin.com/ and create a link. Paste the link here.

thanks

**Comment by maniish** [comment]
Thanks for quick reply. Following is the part of debug file.

https://pastebin.com/dXxqazbd

and this is full log : https://pastebin.com/rNRUsFTK

**Comment by maniish** [comment]
It is resolved by disabling the windows application firewall plugin. Might be something is wrong with miniorange and this plugin. Thank you anyway. Pleaswe close the issue

**Comment by aaron13100** [comment]
This was possibly due to an issue with ajax or a conflict with jQuery for sending the value of the input field "redirect_to_data_field_id" in addManualRedirectPageSearchDropdown.html, which was empty on the server side.
