### ISSUE TITLE
x-redirect-by 404-solution/404-solution.php

### ISSUE THREAD

**Issue by onemillionplaces** [aaron13100/404solution#29]
Hi,

when I check my site with GTmetrix I gor 3 different header entries with "seite-nicht-verfügbar":
https://gtmetrix.com/reports/one-million-places.com/s3mfRjir/

Response Version - HTTP/2.0
--
cache-control | no-cache, must-revalidate, max-age=0
content-encoding | br
content-length | 174
content-security-policy | upgrade-insecure-requests
content-type | text/html; charset=UTF-8
date | Sat, 27 Feb 2021 17:15:51 GMT
expect-ct | max-age=7776000, enforce
expires | Wed, 11 Jan 1984 05:00:00 GMT
location | https://one-million-places.com/seite-nicht-verfuegbar
referrer-policy | no-referrer-when-downgrade
server | LiteSpeed
set-cookie | abj404_solution_REQUEST_URI=%2Fimages%2Flogo%2Flogo.png; expires=Sat, 27-Feb-2021 17:19:51 GMT; Max-Age=240; path=/; secure
set-cookie | abj404_solution_REQUEST_URI_SHORT=%2Fimages%2Flogo%2Flogo.png; expires=Sat, 27-Feb-2021 17:15:56 GMT; Max-Age=5; path=/; secure
status | 301
strict-transport-security | max-age=63072000; includeSubDomains; preload
vary | Accept-Encoding,User-Agent,Accept-Encoding
x-content-type-options | nosniff
**x-redirect-by | 404-solution/404-solution.php**
x-xss-protection | 1; mode=block

Is this a bug? I can´t find any problems on the post. What´s the problem here?

Michael

**Comment by aaron13100** [comment]
What is the issue or malfunction that your seeing? What is not working for you?

**Comment by aaron13100** [comment]
What are you doing and what is the expected result?

**Comment by onemillionplaces** [comment]
I wonder why in GTmetrix the error with "page-not-available" appears 3 times under Waterfall > HTML. And when I open it, I think it´s coming from your plugin. And I was wondering what causes this, if this is a bug and how to fix it?

![Screenshot_2021-02-27 GTmetrix Performance](https://user-images.githubusercontent.com/67807397/109400761-d0a5ce00-794a-11eb-8946-9c371d60a56f.png)

**Comment by aaron13100** [comment]
Yeah, I wonder why too. However, while this is interesting, it doesn't seem to be something that affects the user experience too much (or at all), so it's not interesting enough to motivate me to look into why it's happening. In other words I don't think this is something that negatively affects functionality.
