### ISSUE TITLE
Same 404 being auto created for every post, sometimes in multiple...about building a financial foundation

### ISSUE THREAD

**Issue by WonderGeekWoman** [aaron13100/404solution#30]

**Comment by aaron13100** [comment]
This isn't happening for me. Any idea how to reproduce it? You could try disabling other plugins and creating a post to test it.

Please give me a list of the other plugins you have installed.

thanks

**Comment by WonderGeekWoman** [comment]
ConvertKit, Crocal Extension, Envato Market, Forminator, GA Google Analytics, Lead Forensics, SmartCrawl, Smush, and Yoast Duplicate Post.

I made a new post without using "Clone" and the new post does not have the auto 404, but yet another duplicate auto redirect for last night's new post was created 5 minutes ago. Then I did another one using "Clone" and bingo, another auto "build-your-financial-foundation" redirect. So it appears to be connected to the Yoast Duplicate Post plugin...why would it do that?

**Comment by aaron13100** [comment]
I installed those plugins, including Yoast Duplicate Post, but not including the Crocal Extension since it's not free, and I can't reproduce the issue. Can you: 
1) Enable debug logging (Settings -> 404 Solution -> Options -> Advanced Etc -> Debug logging -> Check the box -> Scroll down and click Save Settings)
2) Create a post that causes the 404 to be created.
3) Verify that the 404 appears (that the issue happened)
4) delete the post if you want
5) View the debug log (Settings -> 404 Solution -> Options -> Advanced Etc -> View the debug file)
6) Paste the entire log or the last 10 pages or so to http://pastebin.com/. 
7) Paste the link created at http://pastebin.com/ here so I can see the log. 

? 

That might be helpful.

regards

**Comment by WonderGeekWoman** [comment]
Interesting. First I cloned the one that I had just made from scratch and it didn't do the auto-404 thing. Then I cloned one of my cloned new posts and it did create the auto-404. So I cloned a very old post that had been migrated from our old website....it also did NOT create an auto-404. So...it has to be something to do with the template our web designer created to clone.

Here is the link: https://pastebin.com/0eymDMF1.

**Comment by aaron13100** [comment]
Does the page you tested with have the slug "/tshirt" ?

It looks like the user agent has "sqldatapartners" in it. Maybe add "sqldatapartners" on a line by itself under the "Internal Process User Agents - Do Not Log" section in the options. (Settings -> 404 Solution -> Options -> Advanced Settings Etc -> Internal Process User Agents - Do Not Log). Then Save Settings ...

Let me know if that fixes it.

**Comment by WonderGeekWoman** [comment]
No, it's not the /tshirt slug. It's when I clone the Podcast Template post or a post that was cloned from that post.

Putting "sqldatapartners" in the Internal Process section won't break all of my 404s? Don't they all use "sqldatapartners"?

Sidenote: I see in the Files and Folders Ignore Strings - Do Not Process, there are three things, but also a warning to leave it blank. I didn't put them in there. Should I just leave it alone?

**Comment by aaron13100** [comment]
Adding sqldatapartners there won't break your 404s. The "Internal Process User Agents - Do Not Log" ignores strings based on the user agent. So it will only ignore 404s if that string is in the user agent. What we're seeing is not a normal user agent - the whole thing is "WordPress/5.6.2; https://sqldatapartners.com", which looks like an internal process or a crawler. A normal user agent is something like "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" or "Opera/9.80 (Macintosh; Intel Mac OS X; U; en) Presto/2.2.15 Version/10.00" or "Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0)" 

So you can safely add "sqldatapartners" to the "Internal Process User Agents" section with no worries. 

Just leave the "files and folders section" alone. Maybe you have the default strings of wp-content/plugins/*, wp-content/themes/*, and .well-known/acme-challenge/* which are supposed to be there.

**Comment by aaron13100** [comment]
Also what is the slug/URL that you tested with? 

thanks

**Comment by WonderGeekWoman** [comment]
The following slugs created the financial 404 (cloned from my SDP Podcast Template, which is a draft, but has been accidentally published previously and moved back to draft status):
/episode-fifth-nothing
/episode-second-nothing
/episode-220-microsoft-ignite-recap
(and previous /episode-#-title) posts

The following slugs did not (cloned from "Episode nothing", which was created from scratch...or the old post "Grant Access..."):
/grant-access-to-tables-clone
/episode-fourth-nothing
/episode-third-nothing
/episode-nothing

I added "sqldatapartners" to Internal Process and then created "Episode sixth nothing" and it still automatically produced the financial-foundation 404.

**Comment by aaron13100** [comment]
ok. I'll look in the code where it says ...  "Added automatic redirect after slug change" and get back to you.

**Comment by WonderGeekWoman** [comment]
Thank you! No rush

**Comment by WonderGeekWoman** [comment]
So bizarre...a few of the autos that were made yesterday have just disappeared...but it created yet another repeat of Episode 220's auto 404 today.

**Comment by aaron13100** [comment]
Please try version 2.23.9

**Comment by WonderGeekWoman** [comment]
Okay, I upgraded and tested again. No new auto 404s about building financial foundations for either new or cloned posts! I'll let you know if Episode 220 gets anymore repeats. Thank you!
