### ISSUE TITLE
PHP Error, Breaking entire wordpress

### ISSUE THREAD

**Issue by jsammarco** [aaron13100/404solution#31]
I found that your plugin breaks my entire wordpress after an update.
On line 719 of SpellChecker.php - PLEASE remove " : int" on the function "getMaxAcceptableDistance"
I have disable auto updates on your plugin because of this.
Maybe this works on newer versions of PHP but not ~5.6

**Comment by aaron13100** [comment]
Hey Joseph. Thanks for reporting this so quickly. I removed the offending line but I don't have a testing environment with PHP 5.6 so let me know if it works now and if/when it breaks again. Please try version 2.24.2.

**Comment by aaron13100** [comment]
Since there's been no response for a while I'll assume this works now. Let me know if that's not the case.

**Comment by jsammarco** [comment]
Hey sorry, didn't see your message. I haven't tested but if that was done I'm sure its fine now. That fixed it for me.
Take care
