### ISSUE TITLE
 Uncaught TypeError: property_exists():

### ISSUE THREAD

**Issue by takwing** [aaron13100/404solution#36]
#### What Version I'm Using
v2.29.0

#### What I Expected To Happen
WP Admin panel can be loaded

#### What Happened Instead
wp admin panel crashed

#### Steps to Reproduce the Bug
FYI, I updated Site Kit by Google to latest version (1.93.0) in wp admin panel and the wp admin panel cannot be loaded.

#### Debug Lines or Stack Trace
==================
File /public_html/edu/wp-content/plugins/404-solution/includes/WordPress_Connector.php 的第 104 行 發生錯誤 (error occurred at line 104)  (Error Type: E_ERROR)。ErrorMessage: Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in /public_html/edu/wp-content/plugins/404-solution/includes/WordPress_Connector.php:104
Stack trace:
#0 /public_html/edu/wp-content/plugins/404-solution/includes/WordPress_Connector.php(104): property_exists(Array, 'slug')
#1 /public_html/edu/wp-includes/class-wp-hook.php(308): ABJ_404_Solution_WordPress_Connector::excludePluginsFromAutoUpdate(NULL, Array)
#2 /public_html/edu/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#3 /public_html/edu/wp-admin/includes/update.php(1088): apply_filters('auto_update_plu...', NULL, Array)
#4 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Util/Auto_Updates.php(105): wp_is_auto_update_forced_for_item('plugin', NULL, Array)
#5 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Util/Auto_Updates.php(54): Google\Site_Kit\Core\Util\Auto_Updates::sitekit_forced_autoupdates_status()
#6 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Authentication/Authentication.php(932): Google\Site_Kit\Core\Util\Auto_Updates::is_plugin_autoupdates_enabled()
#7 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Util/Method_Proxy_Trait.php(25): Google\Site_Kit\Core\Authentication\Authentication->inline_js_base_data(Array)
#8 /public_html/edu/wp-includes/class-wp-hook.php(308): Google\Site_Kit\Core\Authentication\Authentication->Google\Site_Kit\Core\Util\{closure}(Array)
#9 /public_html/edu/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#10 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(721): apply_filters('googlesitekit_i...', Array)
#11 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(356): Google\Site_Kit\Core\Assets\Assets->get_inline_base_data()
#12 [internal function]: Google\Site_Kit\Core\Assets\Assets->Google\Site_Kit\Core\Assets\{closure}('googlesitekit-b...')
#13 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Script_Data.php(51): call_user_func(Object(Closure), 'googlesitekit-b...')
#14 [internal function]: Google\Site_Kit\Core\Assets\Script_Data->Google\Site_Kit\Core\Assets\{closure}('googlesitekit-b...')
#15 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Asset.php(129): call_user_func(Object(Closure), 'googlesitekit-b...')
#16 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(979): Google\Site_Kit\Core\Assets\Asset->before_print()
#17 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(988): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks(Object(WP_Scripts), Array)
#18 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(988): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks(Object(WP_Scripts), Array)
#19 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(988): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks(Object(WP_Scripts), Array)
#20 /public_html/edu/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(154): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks(Object(WP_Scripts), Array)
#21 /public_html/edu/wp-includes/class-wp-hook.php(308): Google\Site_Kit\Core\Assets\Assets->Google\Site_Kit\Core\Assets\{closure}('')
#22 /public_html/edu/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#23 /public_html/edu/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#24 /public_html/edu/wp-admin/admin-header.php(146): do_action('admin_print_scr...')
#25 /public_html/edu/wp-admin/admin.php(239): require_once('/home2/takwing1...')
#26 {main}
  thrown

**Comment by aaron13100** [comment]
Hello.

Please update to the latest version of the plugin and let me know if the issue persists.

thanks

**Comment by takwing** [comment]
I installed the latest version by uploading the zip to my wordpress then activate it.  It looks good!  

thank you for your prompt response

**Comment by aaron13100** [comment]
Thank you for reporting the issue.
