### ISSUE TITLE
Import redirect lists feature?

### ISSUE THREAD

**Issue by Noado** [aaron13100/404solution#37]
I love 404 Solution more than other plugin making 301 redirects. I would like to transfer all redirects data from other plugin to 404 solution, but i can't find import button.

#### What Version I'm Using
DB version: 2.32.2, PHP: 8.2.8, WordPress: 6.2.2, MySQL: 5.7.27, WP Memory Limit: 40M, mbstring Extension: true, [2.32.2]
#### What I Expected To Happen
I exprected if there is export, there should be import too
#### What Happened Instead
Can't find import button
#### Steps to Reproduce the Bug
open "Tools" tab
#### Debug Lines or Stack Trace
-

**Comment by aaron13100** [comment]
What other plugin are you using or can you provide an example file so I can see the format?
thanks

**Comment by Noado** [comment]
I used simple-301-redirects before. It has a CSV export (and import) feature with this simple structure:
```
request,destination
/?p=442,/mr5-avto-u-obochiny/
```
Your export file is more complex:
```
from_url,status,type,to_url,wp_type
/apple-touch-icon-precomposed.png,Captured,404,, 
```
but csv can be easily transformed so that's not a problem. I've already done monkey work to copy-paste from simple-301-redirects to 404 solution, but i think if there's export, there should be import too.

**Comment by aaron13100** [comment]
If I understand your message correctly, you figured out your own way to import the redirects.

In any case, I added an import functionality to the Tools page in version 2.33.0.

**Comment by Noado** [comment]
Yes, all correct. Thanks.
