### ISSUE TITLE
Updating from version 2.35.15 results in no existing redirects shown

### ISSUE THREAD

**Issue by lonesync** [aaron13100/404solution#39]
When proceeding to update from 2.35.15 - all existing redirects disappear, have tried with each version since and for some reason it's the same experience.  Including manual/automatic redirects, basically it's like a fresh install.

- Tried simply updating plugin
- Tried removing plugin and re-install

Each time have to restore back to original, otherwise redirects are no longer available.

Have been using 404 solution for years, first time seeing this type of behavior.

**Comment by aaron13100** [comment]
Probably it's related to the table names being renamed from uppercase to lowercase. If you can use phpmyadmin (for example) to look at the tables you could check.

**Comment by aaron13100** [comment]
You could try exporting the redirects and then importing them. Honestly though I've never tested that so definitely verify the format before importing.

**Comment by lonesync** [comment]
Much appreciate your insight, i will take a look at the tables and try export/import.

**Comment by lonesync** [comment]
When updating to latest version:

- duplicate tables are created (lower/upper case)
- lower case have current data (redirects/logs...)
- remove upper case tables and plugin mentions critical error
- rename lower case tables to upper case resolves critical error and resumes as normal.

Export / Import failed - could be due to amount of redirects 16K+ (captured/ignored)

Within WP database all other table prefixes are upper-case, is it required to have lower case for this plugin?

**Comment by aaron13100** [comment]
As far as I know the plugin can only work with lowercase table names. I'm not sure why it might function correctly with only uppercase names as all queries etc are written to user lowercase names.

**Comment by aaron13100** [comment]
The change to all lowercase was made in 2.35.16 and the issue arrises because of the lower_case_table_names setting in mysql.

**Comment by lonesync** [comment]
Okay, at least the cause/solution has been found and will watch this if an error comes up as a result.  

In theory, was the update supposed to rename existing tables to lower case?  But you feel the lower_case_table_names settings wouldn't allow for this?  Which is why duplicates have been created?

**Comment by aaron13100** [comment]
Yes, in theory, the change was supposed to rename upper case tables to lower case.

When I say the issue arrises because of the lower_case_table_names I just mean that with a setting of `1` there is no issue and that the problem only arrises when lower_case_table_names is set to `0` to make table names case sensitive.

I don't know what went wrong with the renaming in your case, maybe 404's being captured at the same time the renaming was happening. 

I feel that if your table names stay upper case it will probably cause issues in the future though, as I believe the plugin will try to rename them every time there's an update and possibly every night when the maintenance is run.

**Comment by lonesync** [comment]
When maintenance is run, this indeed recreates tables which need to be removed and updated with same steps as above.  Still in upper case in order to resume as normal.

My concern is changing the setting from 0 to 1 - what other problems this may daisy chain through for other apps using the database server.

**Comment by aaron13100** [comment]
Yeah, I would be concerned about that too because there are many other plugins that you have (I assume). 

So when you leave only the lower case tables it doesn't work?

**Comment by lonesync** [comment]
Unfortunately not, the plugin displays the critical error notification with no redirects available.

Basically we don't need to change the database setting, just find why it's not liking lower case - but once resolved we can manually set the table prefix, as it's a one time change after solving and leave the rest running smooth.

**Comment by aaron13100** [comment]
well, do you want to send me the error you're seeing when the table names are lower case? or attach it to pastebin if it's too long?

**Comment by lonesync** [comment]
Updated each table prefix one by one, to see if it's looking at one or all.  With each update back to upper-case, additional functionality would surface, such as redirects would show, then logs...etc.  So all need to be upper to work, however logs are showing an error about not able to find lower case as here.

--
WP_Hook->do_action, WP_Hook->apply_filters, ABJ_404_Solution_View::handleMainAdminPageActionAndDisplay, ABJ_404_Solution_View->echoChosenAdminTab, ABJ_404_Solution_View->echoAdminCapturedURLsPage, ABJ_404_Solution_View->getCapturedURLSPageTable,...PHP message: WordPress database error Table '*****.G4FVXgj_abj404_logsv2' doesn't exist for query
--

In this error, it's looking for logs table in upper-case, but saying it doesn't exist when it does.  And confirmed with logs only showing when using upper-case.

**Comment by aaron13100** [comment]
Well, that's not much to go on. How about pasting the entire log file to pastebin (for example)?  
On the WordPress plugins page there's a link to the Debug Log for the plugin.
![Screenshot 2024-11-22 at 07 24 10](https://github.com/user-attachments/assets/e5983399-4aeb-4689-9f87-f7bab7f332e2)

 Can you see the contents of that? Can you paste all of that to pastebin or attach it here?

**Comment by lonesync** [comment]
[abj404_debug_18b1ebb9d00b1b.txt](https://github.com/user-attachments/files/17865992/abj404_debug_18b1ebb9d00b1b.txt)

Here is current debug log.

**Comment by aaron13100** [comment]
Do you know what the "Studio database error" message means? I can't figure out what that is but it seems likely maybe there's a layer between wordpress and the mysql database or maybe it's not a mysql database?

**Comment by aaron13100** [comment]
Ah I see what may be the issue. It seems to be renaming the tables to all lower case eg g4fvxgj_abj404_lookup but then querying for G4FVXgj_abj404_lookup where the prefix is still upper case. I'll try to make a change today to make sure the prefix is set to lower case also and hopefully that will fix it.

**Comment by aaron13100** [comment]
So I just released version 2.35.24. Please let me know if that fixes it by making it work with lower case table names.  If not please send me the new log file.
thanks

**Comment by lonesync** [comment]
[abj404_debug_18b1ebb9d00b1b.txt](https://github.com/user-attachments/files/17874180/abj404_debug_18b1ebb9d00b1b.txt)

Okay update is smoother, with a couple errors but overall tables look better.

- Update did cause wp-admin to display 'critical error'
- Deactivating and Reactivating behind the scenes corrected access to wp-admin
- Database tables are now in lower-case with no duplicates
- Redirects are showing and working, with exception in 'stats' - which displays 'There has been a critical error on this website.'
- Current debug log is attached

Making progress, which is nice :)

**Comment by aaron13100** [comment]
Thank you for the additional debug log. I've found many other inconsistencies with how table prefixes were handled and I'll release a new version probably tomorrow to address them.

**Comment by lonesync** [comment]
[abj404_debug_18b1ebb9d00b1b.txt](https://github.com/user-attachments/files/17876889/abj404_debug_18b1ebb9d00b1b.txt)

Sounds good and your welcome, there does seem to be others like you say - plugin deactivated and couldn't be activated again.  Have restored to previous version to keep things stable, and attached updated debug just prior to restoring.

**Comment by aaron13100** [comment]
Hey let me know how 2.36.1 works out when you have a chance!

**Comment by lonesync** [comment]
Upgrade is smooth :)  

- Database tables are now in 'lower-case' and no duplicates.
- Allowed maintenance interval to run and also smooth.

All is looking good and much appreciated!

**Comment by aaron13100** [comment]
Thank you for your time spent on this.
