### ISSUE TITLE
Add '301 to Homepage' Dropdown Option in Captured 404 URLs Tab

### ISSUE THREAD

**Issue by aaron13100** [aaron13100/404solution#4]
_From @totalfood on October 3, 2016 16:15_

#### What I Expected To Happen

We were looking for an simpler way to do a '301 to Homepage' in the Captured 404 URLs tab.  
#### What Happened Instead

Each Captured 404 URL has to be individually directed to Homepage
#### Potential Solution

Add a '301 to Homepage' option to the "Mark As Ignored/Trash" Dropdown Menu in the Captured 404 URLs tab. Set "Homepage:" field in Options tab. This would save a LOT of time, especially if you have a lot of 404s! Thank you. 

![screen shot 2016-10-03 at 12 04 04 pm](https://cloud.githubusercontent.com/assets/22596375/19044567/e9b63f7e-8962-11e6-9614-116de31493a7.png)
![screen shot 2016-10-03 at 12 07 13 pm](https://cloud.githubusercontent.com/assets/22596375/19044568/e9b6ca3e-8962-11e6-93a9-bb5f4b305e65.png)

_Copied from original issue: ThemeMix/redirectioner#23_

**Comment by aaron13100** [comment]
_From @scidave on October 8, 2016 15:9_

Completely agree with totalfood, and the proposed solution is a great start.

But I have quite a few pages on my site I send redirects to and managing them one at a time is oh so tedious.  So a "301 to homepage" option would be a great time saver, but I'd like to ask for one more addition:

Today, when I want to do a 301 redirect, the edit button on the captured 404 screen sends me to the screen where I can select what post or page to send the captured 404 to. It would be great if I could check several  captured 404's on that screen ... have the drop down give me the option to "select redirect URL" ... and then go to the URL selection screen.

When I select the desired redirect URL, it gets applied to all the captured 404 boxes checked. 

I would pay for a pro version just to have that time saver! 

Thanks!

**Comment by aaron13100** [comment]
I'm assuming this is no longer necessary with the addition of the optional default 404 destination page that redirects all unmatched 404s to a specific page.

**Comment by scidave** [comment]
I’m not sure what you mean by the last comment  ...  I don’t see any changes in my plugin and I think it is up to date.

 Also, my request remains the same … I moved a large site from a standard html page to wordpress and I don’t redirect captured 404’s all to the same default page.  I would just Love to have the option, as stated in the solution #4 thread … to select several captured 404’s on the first screen and when I click “edit”, the link I type in is what all the checked captured 404’s go to.  Right now I have to do one at a time and although it works, that process could be oh so much easier.

Thanks

Dave

**Comment by aaron13100** [comment]
Hey Dave, I didn't know you'd be able to see this message. Sorry for the confusion. I created a different plugin that I've submitted to WordPress that hasn't been accepted there yet. It's this other, new plugin that's been changed, not the one you have installed...

**Comment by scidave** [comment]
Ah … now I’m excited!  Thanks Aaron … let me know when it’s available!

Dave

**Comment by aaron13100** [comment]
Hey Dave. The plugin is live now if you want to try it out.

**Comment by scidave** [comment]
Thanks Aaron

I installed it on a test site.  The auto suggestion is nice and the auto redirect works like before.

But it still doesn’t allow me to select several of the captured 404’s and send them all to the same page at the same time.  I see the drop down option, which is good, but just one URL in there as a default doesn’t help me as much as it could.

As mentioned on past emails, I moved a fair sized html site over to wordpress so every url changed.  Some of the 404’s need to go to the home page, some to about, some to a specific post on the site, some to trash, some to a nice hacker message, etc.  Moving them one at a time as the 404’s come in works, and your plugin certainly helps with that, but it is pretty tedious.

So what I was saying about willing to pay for a premium version was … I could really use the ability to check multiple boxes on the capture 404 screen, and when I hit edit, all of those I checked get redirected to the page or post I select on the screen that pops up after that. 

The only difference between what is there now and what’s on my wish list, is to include all the url’s I checked on the capture 404 screen to appear in the URL field area of the 404 Solution: Edit Redirect screen so that they all go to the same url I select in the Redirect to: field.

Maybe easier said than done, but I would pay for the premium part of the plugin to do that for sure.

Having said all that … the new plugin is pretty nice!

Thanks Aaron

Dave York
aka
“Science Dave”
http://how-things-work-science-projects.com

**Comment by aaron13100** [comment]
I added "Create a redirect" to the dropdown list of actions that can be applied to captured 404s. Let me know if it works.

**Comment by scidave** [comment]
Aaron

I think that’s exactly what’s needed, but when I check more than one box on the captured 404 page and click apply, I get a blank screen and no option to set up the redirect …

Thanks Aaron!

Dave

**Comment by aaron13100** [comment]
Dave,

I'm sorry to hear that... No error message eh? If you're motivated enough you could turn on debugging under Options -> General Settings -> Debug logging and then activate debug logging on your WordPress installation. (https://codex.wordpress.org/Debugging_in_WordPress#Example_wp-config.php_for_Debugging)

It seems like there should be some kind of error that appears there that could give me more information. Otherwise I'll have to make a code change to try to get more information.

**Comment by aaron13100** [comment]
I forgot to mention also to attach or paste the contents of the debug.log in the wp-content folder.

**Comment by scidave** [comment]
Aaron

Well … I set the debug option in the plugin’s general options section
And I added the define('WP_DEBUG', true);  into wp-config for that site.

Did the same test several times with the “create a redirect” drop down, but I could not get a debug.log file to show up and I didn’t see anything in the plugin … /options/log tab for errors.

I tried several times, even used the theme’s sample wp-config to make sure I got the debub code in there right … but no luck.

Sorry

Dave

**Comment by aaron13100** [comment]
No worries Dave. The latest version (1.6.0) should capture whatever error is happening and you should be able to view the log file and send me what's there. You can see the log file from the Options page under General Settings -> Debug logging -> View the debug file. Let me know how it goes!
thanks

**Comment by scidave** [comment]
Thanks Aaron

I checked 3 boxes on the captured 404 url screen, selected the create redirect in the drop down and hit apply.

A blank screen popped up after that like last time.  Here is what the debug file showed for that
and in case that won't let you in, here is the text ...

2017-03-22 15:51:02 (DEBUG): Displaying sub page: options
2017-03-22 15:51:06 (DEBUG): Processing request for action: (none)
2017-03-22 15:51:06 (DEBUG): Displaying sub page: captured
2017-03-22 15:51:06 (DEBUG): Pagination links: 148 total log records found. Table options: {"filter":"3","orderby":"url","order":"ASC","paged":"1","perpage":"25"}
2017-03-22 15:51:06 (DEBUG): Pagination links: 148 total log records found. Table options: {"filter":"3","orderby":"url","order":"ASC","paged":"1","perpage":"25"}
2017-03-22 15:51:35 (DEBUG): Processing request for action: bulkedit
2017-03-22 15:51:35 (DEBUG): In doBulkAction. Action: bulkedit
2017-03-22 15:51:35 (DEBUG): Redirecting for edit: ?page=abj404_solution&subpage=abj404_edit&ids_multiple=906,907,91
2017-03-22 15:51:42 (DEBUG): Processing request for action: (none)
2017-03-22 15:51:42 (DEBUG): Displaying sub page: redirects
2017-03-22 15:51:42 (DEBUG): Pagination links: 244 total log records found. Table options: {"filter":"0","orderby":"url","order":"ASC","paged":"1","perpage":"25"}
2017-03-22 15:51:42 (DEBUG): Pagination links: 244 total log records found. Table options: {"filter":"0","orderby":"url","order":"ASC","paged":"1","perpage":"25"}
2017-03-22 15:51:46 (DEBUG): Processing request for action: (none)
2017-03-22 15:51:46 (DEBUG): Displaying sub page: options
2017-03-22 15:51:55 (DEBUG): Processing request for action: (none)
2017-03-22 15:51:55 (DEBUG): Displaying sub page: debugfile

Hope it helps. 

Dave

**Comment by aaron13100** [comment]
Dave, thanks for helping me figure out this issue. I had hoped there would be an error message because those are easier to fix. Frankly I'm quite confused as to what could be happening now. It seems like maybe it's an access issue, but then I think you wouldn't even be able to get to the settings page. 

I'll add some more debug info for the next version so that I can confirm or refute that guess and try to come up with some other ideas. Maybe it's easier to just ask though,

Is the user you're logged in with a normal admin user on the site?
Is there some special circumstance like, is it a multisite installation? 
When you view the installed plugins (Plugins -> Installed Plugins) does the 404 solution plugin have the "Settings" link like in this picture? 

![screen shot 2017-03-23 at 8](https://cloud.githubusercontent.com/assets/16979849/24237412/7403d668-0fa6-11e7-8d76-537e9a3a2c89.jpg)

thanks!

**Comment by aaron13100** [comment]
Also what version of WordPress is it at the bottom right of any admin page? thanks

**Comment by scidave** [comment]
Hi Aaron

There are 3 administrators users, but I am the default.  No special circumstances I am aware of.  This is a junk site that I will probably get rid of.  

Yes, the 404 Solution on the installed plugins page shows the  Settings, Deactivate, Edit link live on there

And it is just a free wordpress install “The WRC Theme Viewer” with Wordpress version 4.7.3 on it.

Tell you what, if you would like to be put on as an admin so you can test and try things out, I’ll do that for you.  Like I said, it is an old crap site I will probably recycle or just turn off at some point in the near future.  I use it as a test site now.

Thanks

Dave

**Comment by aaron13100** [comment]
Sure, we can try that. You can email me via the contact form at wealth-psychology.com if you want to use that to email me the password.

**Comment by scidave** [comment]
Aaron
You should get an email on the login info
Tks
Dave

**Comment by aaron13100** [comment]
Hey Dave,
With access to your site, I figured out the issue!

The issue is specific to your installation. There's a conflict with /home/aieworld/public_html/wp-includes/formatting.php or /home/aieworld/public_html/wp-includes/pluggable.php. Here's the error message.

`Warning: Cannot modify header information - headers already sent by (output started at /home/aieworld/public_html/wp-includes/formatting.php:5081) in /home/aieworld/public_html/wp-includes/pluggable.php on line 1179`

I'll be able to write a fix for this into the plugin for the next update. I'll let you know when that happens.

This has been a fun search. 

cheers

**Comment by scidave** [comment]
Nice!
Thanks Aaron
Dave


Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by totalfood** [comment]
Hi Aaron, I've been following along on your exchanges with Dave. I'm still using 404 Redirected, and would be happy to switch over to 404 Solution soon. 

Just want to verify... how do I transfer over all of the redirects I've already done (or automated) from one plug-in to the other? Let me know. Thanks!

Mark

**Comment by aaron13100** [comment]
Dave, the update's been done and is ready to try out in version 1.6.2. Let me know how it goes!

Mark, thanks for stopping by! :) I created issue #11 for you to take care of that. I'm not sure when I'll be able to get to it, but I will keep that issue updated with any progress.

**Comment by scidave** [comment]
Thanks Aaron

I tried it about every which way I can … sure seems to work!

So … will this become an update to the original plugin?  I also had Mark’s question on not losing the redirects already made by installing this plugin and deleting the first.

Thanks again … this works great!

Dave

**Comment by aaron13100** [comment]
I can probably add something in to copy over existing redirects from the old plugin. I'll update issue #11 with info though. This one has gotten out of hand!

**Comment by totalfood** [comment]
Hi Aaron, I saw you addressed the redirect transfer in the other thread (but closed it), so I'm replying here. I finally went to activate 404 Solution, and but unfortunately got the following:

Plugin could not be activated because it triggered a fatal error.

Fatal error: Call to a member function errorMessage() on a non-object in /chroot/home/totalfoo/totalfood.com/html/wordpress/wp-content/plugins/404-solution/includes/ErrorHandler.php on line 36 Fatal error: Call to a member function errorMessage() on a non-object in /chroot/home/totalfoo/totalfood.com/html/wordpress/wp-content/plugins/404-solution/includes/ErrorHandler.php on line 69

**Comment by aaron13100** [comment]
@totalfood  I created issue #12 for you. You can create issues yourself too. It's here https://github.com/aaron13100/404solution/issues/12.
