### ISSUE TITLE
Having to put in redirection location twice.

### ISSUE THREAD

**Issue by aaron13100** [aaron13100/404solution#6]
_From @grozzy on September 13, 2016 1:50_

Hi there,

I have your great plugin across three sites. Over the past few months though, when I put in a redirection the destination post/page doesn't come up. Instead, I need to sort by view, find that redirection and insert the destination URL after which it then inserts it.

It would be awesome if you could fix this bug.

_Copied from original issue: ThemeMix/redirectioner#21_

**Comment by aaron13100** [comment]
_From @defries on September 13, 2016 6:42_

I need a little bit more explanation, screenshots perhaps as well, to understand what you mean exactly. 
Can you take me through the steps with more detail please? I'd love to fix this bug for you, but as of now I don't know where to start :)

**Comment by aaron13100** [comment]
_From @grozzy on September 14, 2016 10:5_

Sure, happy to help.

**So attached is webmaster tools showing a broken link.**
<img width="100%" alt="webmaster_tools_broken_link_pdf" src="https://cloud.githubusercontent.com/assets/411524/18513065/1eea6f02-7a8c-11e6-9323-bbcc1f237266.png">

**Now, I attempt to address this in 404 redirected.**
<img width="100%" alt="adding_redirect_pdf" src="https://cloud.githubusercontent.com/assets/411524/18513090/39c5f08a-7a8c-11e6-90cd-a8f916c2de49.png">

**As you can see, when i then look at this 301, it is missing the destination URL.**
<img width="100%" alt="redirect_doesn_t_have_a_destination_url_pdf" src="https://cloud.githubusercontent.com/assets/411524/18513110/516040c4-7a8c-11e6-8b61-0668f43bbd31.png">

**I then press edit, add the destination as shown below.**
<img width="100%" alt="edit_redirect_again_pdf" src="https://cloud.githubusercontent.com/assets/411524/18513134/679f43da-7a8c-11e6-9c46-613626dd0d06.png">

**As you can see it now works. But its double handling which gets fustrating.**
<img width="100%" alt="redirect_now_working_pdf" src="https://cloud.githubusercontent.com/assets/411524/18513146/7edb50a2-7a8c-11e6-88b1-ff5f2ecd18f2.png">

**Comment by aaron13100** [comment]
_From @defries on September 14, 2016 13:9_

I made some changes to your comment (changed PDFs for screenshots) and I think I understand what the issue is there. Are you saying that prior to the 1.4.x versions this proces went differently? If so, which part of these steps you just outlined are different?

**Comment by aaron13100** [comment]
_From @cnasal on September 22, 2016 10:48_

@defries I was about to report this same bug, so I wanted to jump in give you more information about what we're experiencing.  If we add a Manual Redirect to an external page, everything works correctly.  However, if we create a Manual Redirect and choose an internal page, then it adds the redirect but with no destination (as shown in the 3rd screenshot by @grozzy):

![](https://cloud.githubusercontent.com/assets/411524/18513110/516040c4-7a8c-11e6-8b61-0668f43bbd31.png)

If you then edit that Manual Redirect and choose the page again, it saves and works correctly.

Let me know if you need any more information, and I'll be happy to provide it.

Thanks,
Carl

**Comment by aaron13100** [comment]
_From @defries on September 22, 2016 13:26_

Thanks. I think I understand the issue now. I’ll look into it as soon as
I’m out of this hectic phase, which may take a few weeks, but I will find a
solution for this and update accordingly.

**Comment by aaron13100** [comment]
_From @cnasal on September 22, 2016 15:30_

Thanks @defries!

**Comment by aaron13100** [comment]
I can't reproduce this and much of the plugin has been refactored, so I'm closing this. If the bug persists please activate debug mode in settings, activate the DEBUG_LOG in WordPress, and report back here.

**Comment by raglannyc** [comment]
I am having the same problem. I create a manual redirect to an internal page, and the redirect is created with no destination. I have to edit the redirect and select the internal page again, and this time it saves the destination. See the 3rd item in my screenshot, "asdfasdf":

![screen shot 2017-04-23 at 6 59 49 pm](https://cloud.githubusercontent.com/assets/12042994/25318164/1adf13e4-2857-11e7-8fa0-a19bbca2175f.png)

I don't see any "debug mode" in Redirectioner settings, so not sure what to do there, please advise.

Redirectioner 1.4.9, WordPress 4.7.4, Flywheel hosting, PHP v5.6.30, MySQL v5.6.32

**Comment by aaron13100** [comment]
Hi raglannyc. You have the "Redirectioner" plugin and the plugin I've made is called "404 Solution!" It's not the same plugin so I won't be able to help. If you want to try "404 Solution" there is an option under the "Tools" tab to import redirects from the Redirectioner plugin.
