### ISSUE TITLE
Move ALL Captured 404 URLs to Trash

### ISSUE THREAD

**Issue by aaron13100** [aaron13100/404solution#8]
_From @fdeitelhoff on July 3, 2016 19:21_

#### What I Expected To Happen

A new button in the "Captured 404 URLs" tab would be awesome that moves all captured 404 urls to the trash. 
#### What Happened Instead

I have to select them manually one by one and moving them just in 25er batches. And this time I have 297 pages of captured urls to this is a huge time waste.

_Copied from original issue: ThemeMix/redirectioner

**Comment by aaron13100** [comment]
_From @defries on July 6, 2016 11:6_

Thanks for reporting @fdeitelhoff. Sounds like a solid feature and we'll look into it how to best approach this.

**Comment by aaron13100** [comment]
This is corrected with the future release of version 1.6.5 by adding the "All" option to the "rows per page" option on the Captured 404s page. As a workaround for the current version, open the Captured 404s page, then add `&perpage=10000` to the URL and press enter.

**Comment by fdeitelhoff** [comment]
@aaron13100 Many, many thanks!

**Comment by remkus** [comment]
Out of curiosity, Aaron, why did you opt for a full fork instead of a pull
request and help us fix the one we took over?

**Comment by aaron13100** [comment]
Hey defries! Thanks for stopping by. "Personal reasons." I know it generally doesn't make sense to create yet another new plugin when there's already one out there, because who needs 100 plugins that do exactly the same thing, right? But there are a few reasons. It looks like the original is going towards a "pro" vs "free" model that I wouldn't be able to profit from (based on the issue labels). I want to have full control over the functionality decisions because I think it's more fun that way. And I want to be able to add a link directly to my website somewhere in the plugin, which wouldn't really make sense being only a contributer and not the owner. 

Those three reasons, plus what seems like not that much activity on the original. I had a cruddy experience with a completely unrelated plugin, contributing my time only to have my work virtually ignored (https://github.com/essiembre/eclipse-rbe/pull/48). So I also wanted to avoid that possibility as well.

I figured it didn't make any sense to ask for everything I wanted above without having "proven myself." No hard feelings I hope.

-Aaron

**Comment by remkus** [comment]
No hard feelings, but you could've asked first what our stance and plans
are :)

**Comment by aaron13100** [comment]
Yeah, you're right. Honestly I was hoping you wouldn't notice and I didn't know the issues would be linked forever when I copied them. I'll close and recreate the related tickets so you guys won't be bothered anymore.

What are your stance and plans on the issue, by the way?

**Comment by remkus** [comment]
We are working on a complete and full rewrite. The current code is just not
up to spec for high-performance sites, nor is it stable enough to use to
expand on.
